apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
        - name: grpc-server
          image: "{{ .Values.image.repository }}grpc_server:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 50051
          env:
            - name: DB_HOST
              value: "postgresql"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "{{ .Values.postgresql.auth.username }}"
            - name: DB_PASSWORD
              value: "{{ .Values.postgresql.auth.password }}"
            - name: DB_NAME
              value: "{{ .Values.postgresql.auth.database }}"
            - name: RABBITMQ_URL
              value: "amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@rabbitmq:5672/"
            - name: SAVE_EXCHANGE
              value: "SaveMessageExchange"
            - name: NEW_MESSAGE_EXCHANGE
              value: "NewMessageExchange"
