apiVersion: v1
kind: Service
metadata:
  name: grpc-server
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: grpc-server
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 50051
