replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 50051

postgresql:
  auth:
    username: postgres
    password: password
    database: chatdb

rabbitmq:
  auth:
    username: guest
    password: guest

resources: {}
nodeSelector: {}
tolerations: []
affinity: []
